# Example TOML configuration for full system (hardware + cameras + tag IDs)


[steppers.chute]
board = "DISTRIBUTOR"
index = 0
steps_per_revolution = 200
current_run_percent = 80
current_hold_percent = 30
current_hold_delay = 8
microsteps = 16


[steppers.carousel]
board = "FEEDER"
index = 3
steps_per_revolution = 200
current_run_percent = 80
current_hold_percent = 30
current_hold_delay = 8
microsteps = 16


[steppers.bulk_rotor]
board = "FEEDER"
index = 0
steps_per_revolution = 200
current_run_percent = 80
current_hold_percent = 30
current_hold_delay = 8
microsteps = 16


[steppers.rotor1]
board = "FEEDER"
index = 1
steps_per_revolution = 200
current_run_percent = 80
current_hold_percent = 30
current_hold_delay = 8
microsteps = 16


[steppers.rotor2]
board = "FEEDER"
index = 2
steps_per_revolution = 200
current_run_percent = 80
current_hold_percent = 30
current_hold_delay = 8
microsteps = 16

[digital_inputs]
chute_home = ["DISTRIBUTOR", 0]
carousel_home = ["FEEDER", 3]

[digital_outputs]
feeder_lights = ["FEEDER", 0]

[cameras.feeder]
device_index = 0
width = 1920
height = 1080
fps = 30

[cameras.classification_bottom]
device_index = 1
width = 1920
height = 1080
fps = 30

[cameras.classification_top]
device_index = 2
width = 1920
height = 1080
fps = 30

[tags]
first_c_channel_aruco_tag_id = 86
second_c_channel_aruco_tag_id = 815
third_c_channel_aruco_tag_id = 957
